"""add customer_health_scores table

Revision ID: cfdd6c74ce4c
Revises: 7f19909f0567
Create Date: 2026-07-12 16:32:16.885564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdd6c74ce4c'
down_revision: Union[str, None] = '7f19909f0567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_health_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('health_status', sa.Enum('healthy', 'at_risk', 'critical', name='health_status_enum'), nullable=False),
    sa.Column('rfm_recency', sa.Float(), nullable=False),
    sa.Column('rfm_frequency', sa.Float(), nullable=False),
    sa.Column('rfm_monetary', sa.Float(), nullable=False),
    sa.Column('component_breakdown', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_health_scores_health_status'), 'customer_health_scores', ['health_status'], unique=False)
    op.create_index(op.f('ix_customer_health_scores_score_date'), 'customer_health_scores', ['score_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_health_scores_score_date'), table_name='customer_health_scores')
    op.drop_index(op.f('ix_customer_health_scores_health_status'), table_name='customer_health_scores')
    op.drop_table('customer_health_scores')
    # ### end Alembic commands ###
