import { Box } from '@mui/material'
import PriorityHighRoundedIcon from '@mui/icons-material/PriorityHighRounded'
import ListAltRoundedIcon from '@mui/icons-material/ListAltRounded'
import ReportProblemOutlinedIcon from '@mui/icons-material/ReportProblemOutlined'
import PublicOutlinedIcon from '@mui/icons-material/PublicOutlined'
import { KpiCard } from '../components/dashboard/KpiCard'
import { PageIntro } from '../components/common/PageIntro'
import { SectionCard } from '../components/common/SectionCard'
import { RecommendationList } from '../components/recommendations/RecommendationList'
import {
  useAllRecommendations,
  useCustomerRecommendations,
  useHighPriorityRecommendations,
  useRegionalRecommendations,
  useRiskRecommendations,
} from '../hooks/useRecommendationQueries'
import { formatNumber } from '../utils/format'

export default function Recommendations() {
  const all = useAllRecommendations()
  const highPriority = useHighPriorityRecommendations()
  const customerRecs = useCustomerRecommendations()
  const riskRecs = useRiskRecommendations()
  const regionalRecs = useRegionalRecommendations()

  const regionalDeclines = (regionalRecs.data ?? []).filter((r) => r.rule_id === 'regional_revenue_decline')
  const regionalGrowth = (regionalRecs.data ?? []).filter((r) => r.rule_id === 'regional_growth_opportunity')
  const salesAlerts = (all.data ?? []).filter((r) => r.recommendation_type === 'sales')
  const revenueAlerts = [...regionalDeclines, ...salesAlerts].sort((a, b) => b.priority_score - a.priority_score)
  const suggestedActions = (all.data ?? []).slice(0, 8)

  return (
    <>
      <PageIntro description="Every recommendation below is generated by combining Health Scores, Purchase Predictions, and Analytics through business rules — no LLM involved. Ranked by priority so a manager can work top-down." />

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr', md: 'repeat(4, 1fr)' },
          gap: 2.5,
          mb: 4,
        }}
      >
        <KpiCard
          label="Total Recommendations"
          value={formatNumber(all.data?.length ?? 0)}
          icon={<ListAltRoundedIcon fontSize="small" />}
          loading={all.isLoading}
        />
        <KpiCard
          label="High Priority"
          value={formatNumber(highPriority.data?.length ?? 0)}
          icon={<PriorityHighRoundedIcon fontSize="small" />}
          loading={highPriority.isLoading}
        />
        <KpiCard
          label="Critical Customers"
          value={formatNumber(riskRecs.data?.length ?? 0)}
          icon={<ReportProblemOutlinedIcon fontSize="small" />}
          loading={riskRecs.isLoading}
        />
        <KpiCard
          label="Regional Alerts"
          value={formatNumber(regionalDeclines.length)}
          icon={<PublicOutlinedIcon fontSize="small" />}
          loading={regionalRecs.isLoading}
        />
      </Box>

      <SectionCard
        title="Suggested Actions"
        subtitle="The highest-urgency items across every recommendation type, ranked by priority score."
        sx={{ mb: 3 }}
      >
        <RecommendationList
          items={suggestedActions}
          loading={all.isLoading}
          error={all.isError}
          onRetry={() => all.refetch()}
          emptyDescription="No recommendations yet — run health scoring and predictions first."
          skeletonRows={4}
        />
      </SectionCard>

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' },
          gap: 2.5,
          mb: 2.5,
        }}
      >
        <SectionCard
          title="High Priority Customers"
          subtitle="Customers worth contacting this week — high purchase probability and a healthy account."
        >
          <RecommendationList
            items={customerRecs.data ?? []}
            loading={customerRecs.isLoading}
            error={customerRecs.isError}
            onRetry={() => customerRecs.refetch()}
            emptyDescription="No customers currently meet the contact threshold."
          />
        </SectionCard>

        <SectionCard
          title="Critical Customers"
          subtitle="Dormant accounts or a health score that has dropped below the follow-up threshold."
        >
          <RecommendationList
            items={riskRecs.data ?? []}
            loading={riskRecs.isLoading}
            error={riskRecs.isError}
            onRetry={() => riskRecs.refetch()}
            emptyDescription="No customers currently need a risk follow-up."
          />
        </SectionCard>
      </Box>

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' },
          gap: 2.5,
        }}
      >
        <SectionCard
          title="Regional Opportunities"
          subtitle="Regions with strong revenue growth worth reinforcing with more coverage or inventory."
        >
          <RecommendationList
            items={regionalGrowth}
            loading={regionalRecs.isLoading}
            error={regionalRecs.isError}
            onRetry={() => regionalRecs.refetch()}
            emptyDescription="No region is currently showing standout growth."
          />
        </SectionCard>

        <SectionCard
          title="Revenue Alerts"
          subtitle="Regional declines and company-wide demand-forecast swings that need a response."
        >
          <RecommendationList
            items={revenueAlerts}
            loading={regionalRecs.isLoading || all.isLoading}
            error={regionalRecs.isError || all.isError}
            onRetry={() => {
              regionalRecs.refetch()
              all.refetch()
            }}
            emptyDescription="No revenue alerts right now — regions and forecasts look stable."
          />
        </SectionCard>
      </Box>
    </>
  )
}
